"""The fitted reach is a model parameter, and was reported as a measurement.

Finding F9 of the 2026-09-16 pipeline audit. Five defects, and the statistical
one is the one that matters most.

- **It crashed on a short target.** `depth[:usable].reshape(n_bins, bin_size)`
  raises a raw numpy `ValueError` when the target is shorter than one bin, and
  that path is reachable from the command line.
- **Trailing bases were dropped.** `usable = n_bins * bin_size` discards the
  remainder, so up to a bin of the genome never entered the fit.
- **Bins straddled record joins.** A bin spanning the end of one molecule and
  the start of another averages depth across a boundary no polymerase crosses.
- **The kernel clipped rather than wrapped.** On a circular target a site near
  the origin loses the half of its triangle that falls off the end, and the
  loss grows with the reach being tested -- a bias against exactly the large
  reaches the fit exists to consider.
- **The correlation was in-sample.** The reach was chosen by argmax of Spearman
  rho over a grid, and the number reported as evidence was that same maximum,
  on the same data. A maximum over eleven candidates is optimistic by
  construction, and nothing said so.
"""

import numpy as np
import pytest

from neoswga.core.reach_calibration import DEFAULT_REACH_GRID, fit_reach, predicted_depth


def _depth_from(positions, length, reach, noise=0.0, seed=0):
    """Depth generated by a known reach, so a fit has a right answer."""
    profile = predicted_depth(positions, length, reach)
    if noise:
        rng = np.random.default_rng(seed)
        profile = profile + rng.normal(0.0, noise * (profile.std() or 1.0), length)
    return profile


class TestItDoesNotCrash:
    def test_a_target_shorter_than_one_bin_is_not_an_exception(self):
        """Reachable from the command line on a small plasmid."""
        fit = fit_reach(np.ones(400), [100, 200], bin_size=1000)

        assert fit.informative is False
        assert "bin" in fit.note.lower()

    def test_an_empty_depth_array_is_not_an_exception(self):
        assert fit_reach(np.zeros(0), [1]).informative is False

    def test_no_binding_sites_is_not_an_exception(self):
        assert fit_reach(np.ones(10_000), []).informative is False

    def test_too_few_bins_to_correlate_is_reported_not_fitted(self):
        """Two bins correlate perfectly with anything monotone. A number from
        that is not evidence about reach."""
        fit = fit_reach(np.ones(2_500), [100, 2_000], bin_size=1000)

        assert fit.informative is False


class TestEveryBaseCounts:
    def test_the_trailing_partial_bin_is_not_dropped(self):
        """`usable = n_bins * bin_size` discarded up to a bin of the genome."""
        length = 10_500
        depth = _depth_from([5_000], length, 2_000)

        fit = fit_reach(depth, [5_000], bin_size=1000)

        assert fit.n_bins == 11, "the 500 bp tail was dropped"

    def test_a_bin_never_straddles_a_record_join(self):
        """Averaging across a boundary no polymerase crosses mixes two
        molecules into one observation."""
        length = 3_000
        depth = _depth_from([500], length, 1_000)

        fit = fit_reach(depth, [500], bin_size=1000, record_starts=[0, 1_500])

        assert fit.n_bins == 4, (
            "records of 1500 bp each give two full bins and two 500 bp "
            "remainders, not three bins straddling the join"
        )


class TestTheKernelWrapsWhenTheTargetDoes:
    def test_a_site_near_the_origin_keeps_its_whole_triangle(self):
        """Clipping loses more of the triangle the larger the reach, which
        biases the fit against the large reaches it exists to weigh."""
        length = 10_000
        linear = predicted_depth([50], length, 2_000, circular=False)
        circular = predicted_depth([50], length, 2_000, circular=True)

        assert circular.sum() > linear.sum()
        assert circular[-100] > 0, "the wrap did not reach the end of the sequence"

    def test_a_linear_target_still_clips(self):
        profile = predicted_depth([50], 10_000, 2_000, circular=False)

        assert profile[-100] == 0.0

    def test_wrapping_is_refused_for_a_multi_record_prefix(self):
        """Wrapping joins the last record's end to the first record's start,
        which are different molecules."""
        fit = fit_reach(
            np.ones(4_000),
            [100],
            bin_size=1000,
            circular=True,
            record_starts=[0, 2_000],
        )

        assert "circular" in fit.note.lower()


class TestTheCorrelationIsLabelledForWhatItIs:
    def _fit(self):
        length = 200_000
        positions = list(range(5_000, length, 20_000))
        depth = _depth_from(positions, length, 5_000, noise=0.3)
        return fit_reach(depth, positions, bin_size=1000)

    def test_the_in_sample_figure_is_named_in_sample(self):
        fit = self._fit()

        assert fit.in_sample_correlation == fit.correlation

    def test_a_cross_validated_figure_is_reported_beside_it(self):
        """A maximum over eleven candidates on the same data is optimistic by
        construction. Blocked folds hold out contiguous stretches, because
        neighbouring bins are not independent."""
        fit = self._fit()

        assert fit.cv_correlation is not None

    def test_on_unrelated_depth_the_in_sample_figure_is_optimistic(self):
        """The defect, pinned, and pinned ACROSS SEEDS on purpose.

        On depth that has nothing to do with the primers the true correlation
        is zero, so any positive in-sample figure is selection optimism. Over
        twelve seeds it averaged +0.058 -- around a third of the 0.15
        informativeness threshold, from choosing among eleven candidates.

        It is not larger than the fold-to-fold noise, though, so the sign flips
        on individual runs (in-sample was higher on 10 of 12). A test asserting
        the inequality on one seed would pin a coincidence, which is why this
        one measures the mean.
        """
        length = 120_000
        gaps = []
        for seed in range(8):
            rng = np.random.default_rng(seed)
            positions = sorted(rng.integers(0, length, 40).tolist())
            depth = rng.normal(100.0, 10.0, length)  # no primer signal at all
            fit = fit_reach(depth, positions, bin_size=1000)
            assert fit.cv_correlation is not None
            gaps.append(fit.in_sample_correlation - fit.cv_correlation)

        assert np.mean(gaps) > 0, (
            "the in-sample maximum is not showing its upward bias on null "
            "data, so the held-out figure is not measuring what it claims"
        )

    def test_the_note_says_the_result_is_a_model_parameter(self):
        fit = self._fit()

        assert "model parameter" in fit.note.lower() or "sensitivity" in fit.note.lower()


class TestThePlausibleRangeIsReported:
    def _fit(self):
        length = 200_000
        positions = list(range(5_000, length, 20_000))
        depth = _depth_from(positions, length, 5_000, noise=0.3)
        return fit_reach(depth, positions, bin_size=1000)

    def test_a_range_is_given_not_only_a_point(self):
        """A flat optimum means the data cannot tell 3 kb from 20 kb, which is
        a different situation from a sharp one and must not be reported as the
        same number with the same confidence."""
        fit = self._fit()

        assert len(fit.plausible_reaches) >= 1

    def test_the_best_reach_is_inside_it(self):
        fit = self._fit()

        assert fit.best_reach in fit.plausible_reaches

    def test_a_grid_edge_result_is_flagged(self):
        """The true value may be past the end of the grid, and a point estimate
        there is a lower bound rather than an answer. Forced by giving a grid
        that stops well short of the reach that generated the depth."""
        length = 200_000
        positions = list(range(5_000, length, 20_000))
        depth = _depth_from(positions, length, 3_000)

        fit = fit_reach(depth, positions, bin_size=1000, reaches=[500, 1000, 3000])

        assert fit.informative is True
        assert fit.best_reach == 3000
        assert fit.at_grid_edge is True
        assert "may be higher" in fit.note

    def test_a_mid_grid_result_is_not_flagged(self):
        length = 200_000
        positions = list(range(5_000, length, 20_000))
        depth = _depth_from(positions, length, 5_000)

        fit = fit_reach(depth, positions, bin_size=1000, reaches=[500, 5_000, 70_000])

        assert fit.best_reach == 5_000
        assert fit.at_grid_edge is False


class TestItStillRecoversAKnownReach:
    """The accommodations must not cost the thing the fit is for."""

    def test_the_fitted_reach_is_near_the_one_that_generated_the_depth(self):
        length = 400_000
        positions = list(range(10_000, length, 25_000))
        depth = _depth_from(positions, length, 5_000, noise=0.2)

        fit = fit_reach(depth, positions, bin_size=1000)

        assert fit.informative is True
        assert 2_000 <= fit.best_reach <= 10_000, fit.by_reach

    def test_the_payload_carries_the_new_fields(self):
        length = 200_000
        positions = list(range(5_000, length, 20_000))
        fit = fit_reach(_depth_from(positions, length, 5_000), positions, bin_size=1000)

        payload = fit.to_dict()
        for key in ("in_sample_correlation", "cv_correlation", "plausible_reaches", "at_grid_edge"):
            assert key in payload
