"""The `score` stage prepares candidates; it no longer scores them.

Audit finding F0, decided 2026-09-05: retire the random forest from the default
pipeline and keep `step3_df.csv` as a deterministic pass-through of step 2.

The evidence that settled it. On the three GC-tier panels the gate removed 7 of
1222 candidates, 0 of 449, and 0 of 319 -- the scores cluster well above the
default `min_amp_pred` of 10.0, so it passed essentially everything. And every
step-4 consumer reads only the primer column:

    unified_optimizer.py:936        step3_df["primer"].tolist()
    dominating_set_optimizer.py:756 step3_df["primer"].tolist()
    background_aware_optimizer.py:518 step3_df["primer"].tolist()
    primer_expansion.py:699         step3_df["primer"].tolist()

So the score was computed for every candidate and then discarded before
selection. Asked directly whether it identifies good primers, taking the top
half of a pool by `amp_pred` and optimizing over it produced the WORST of five
half-pools (see `tests/test_step3_order_is_deterministic.py`).

The model itself is fit to synthetic data generated by a hand-written rule, so
it reproduces an opinion rather than measured amplification; under the default
`fast_score` the delta-G features are zeroed, making the prediction a pure
function of the primer sequence, blind to the genome and the reaction.

WHAT IS KEPT. The stage still writes `step3_df.csv`, because it is a required
intermediate that six modules read, and it still carries the step-2 measurements
and the deterministic order that `order_step3_rows` establishes. The random
forest is still reachable behind `--amp-model` for anyone who wants it; retiring
it from the default path is not the same as deleting it.
"""

import logging

import pandas as pd
import pytest

_STEP2_ROWS = [
    # primer, ratio, gini, fg_count, bg_count
    ("AAACCCGGGT", 12.0, 0.30, 40, 3),
    ("ACCCGGGTTT", 9.5, 0.30, 33, 4),
    ("AAGGCCTTAC", 7.0, 0.45, 21, 3),
    ("CACCGACGAC", 6.0, 0.45, 18, 3),
    ("TTGGCCAATG", 4.0, 0.55, 12, 3),
]


@pytest.fixture
def primed(tmp_path, monkeypatch):
    """A data_dir holding only step2_df.csv, with the pipeline pointed at it."""
    import neoswga.core.pipeline as pipeline_mod
    from neoswga.core import parameter

    pd.DataFrame(_STEP2_ROWS, columns=["primer", "ratio", "gini", "fg_count", "bg_count"]).to_csv(
        tmp_path / "step2_df.csv", index=False
    )

    monkeypatch.setattr(pipeline_mod, "_initialize", lambda: None)
    monkeypatch.setattr(pipeline_mod, "fg_prefixes", [str(tmp_path / "fg")], raising=False)
    monkeypatch.setattr(pipeline_mod, "fg_seq_lengths", [1_000_000], raising=False)
    monkeypatch.setattr(parameter, "data_dir", str(tmp_path), raising=False)
    monkeypatch.setattr(parameter, "verbose", False, raising=False)
    monkeypatch.setattr(parameter, "min_amp_pred", None, raising=False)
    monkeypatch.setattr(parameter, "use_amp_model", False, raising=False)
    return tmp_path


def _run(primed):
    import neoswga.core.pipeline as pipeline_mod

    pipeline_mod.step3(validate_prerequisites=False)
    return pd.read_csv(primed / "step3_df.csv")


# ---------------------------------------------------------------------------
# The stage no longer scores
# ---------------------------------------------------------------------------


def test_no_amplification_score_column_is_written(primed):
    """A column nothing selects on, and that measures an opinion rather than
    amplification, should not be in the file at all."""
    out = _run(primed)

    for col in ("on.target.pred", "amp_pred"):
        assert (
            col not in out.columns
        ), f"step3_df.csv still carries {col!r}; the scoring stage was retired"


def test_the_model_is_never_loaded(primed, monkeypatch):
    """The cost, not just the column. Retiring the stage must skip the work."""
    from neoswga.core import rf_preprocessing

    called = []
    monkeypatch.setattr(
        rf_preprocessing,
        "predict_new_primers",
        lambda *a, **k: called.append(1) or pd.DataFrame(),
    )
    _run(primed)

    assert not called, "the random forest was still run on the default path"


def test_every_candidate_survives(primed):
    """The gate removed 7 of 1222, 0 of 449 and 0 of 319 on the real panels.
    With no score there is nothing to gate on, and that must be explicit."""
    out = _run(primed)
    assert len(out) == len(_STEP2_ROWS)
    assert set(out["primer"]) == {r[0] for r in _STEP2_ROWS}


# ---------------------------------------------------------------------------
# What the file must still carry
# ---------------------------------------------------------------------------


def test_the_step2_measurements_are_carried_through(primed):
    """`gini` in particular: it leads the row order, and the report reads these."""
    out = _run(primed)
    for col in ("primer", "gini", "ratio", "fg_count", "bg_count"):
        assert col in out.columns, f"step3_df.csv lost {col!r} from step 2"


def test_the_order_is_deterministic_and_led_by_gini(primed):
    """`order_step3_rows` is what makes an unseeded run reproducible; the
    pass-through must not drop it."""
    out = _run(primed)
    assert out["gini"].is_monotonic_increasing
    for _gini, group in out.groupby("gini", sort=False):
        primers = group["primer"].tolist()
        assert primers == sorted(primers)


def test_running_twice_gives_the_same_file(primed):
    first = _run(primed)["primer"].tolist()
    second = _run(primed)["primer"].tolist()
    assert first == second


# ---------------------------------------------------------------------------
# The retired knob must not become another silently-inert option
# ---------------------------------------------------------------------------


def test_min_amp_pred_says_it_no_longer_applies(primed, monkeypatch, caplog):
    """This repository's recurring defect is an option that is accepted and read
    by nothing. Retiring the gate must not create another one."""
    from neoswga.core import parameter

    monkeypatch.setattr(parameter, "min_amp_pred", 15.0, raising=False)

    with caplog.at_level(logging.WARNING):
        _run(primed)

    assert (
        "min_amp_pred" in caplog.text
    ), "min_amp_pred was set to a gating value and silently did nothing; say so"


def test_the_default_threshold_is_not_warned_about(primed, monkeypatch, caplog):
    """Guard the guard: warning on the default would fire on every run."""
    from neoswga.core import parameter

    monkeypatch.setattr(parameter, "min_amp_pred", None, raising=False)
    with caplog.at_level(logging.WARNING):
        _run(primed)

    assert "min_amp_pred" not in caplog.text


# ---------------------------------------------------------------------------
# The escape hatch
# ---------------------------------------------------------------------------


def test_the_model_can_still_be_asked_for(primed, monkeypatch):
    """Retiring it from the default path is not deleting it."""
    from neoswga.core import parameter

    monkeypatch.setattr(parameter, "use_amp_model", True, raising=False)
    out = _run(primed)

    assert "on.target.pred" in out.columns, "--amp-model did not restore the score column"


# ---------------------------------------------------------------------------
# Downstream must not fabricate a number in its absence
# ---------------------------------------------------------------------------


def test_the_report_does_not_invent_a_uniform_quality_rating(tmp_path):
    """Before `a2a58c0` every primer rendered three stars because `amp_pred` was
    missing and fell back to 0.5. With the column now deliberately absent, the
    report must omit the rating rather than reinstate that constant."""
    (tmp_path / "step4_improved_df.csv").write_text(
        "primer,set_index,score,coverage,gini,mean_tm,optimizer\n"
        "AAACCCGGGT,0,1.0,0.9,0.4,32.1,hybrid\n"
        "ACCCGGGTTT,0,1.0,0.9,0.4,31.8,hybrid\n"
    )
    (tmp_path / "step3_df.csv").write_text(
        "primer,gini,ratio,fg_count,bg_count\nAAACCCGGGT,0.4,12.0,40,3\nACCCGGGTTT,0.4,9.5,33,4\n"
    )
    from neoswga.core.report.metrics import collect_pipeline_metrics

    metrics = collect_pipeline_metrics(str(tmp_path))
    assert metrics.primers, "the report failed to build without a score column"
    assert all(
        p.amp_pred == 0 for p in metrics.primers
    ), "a quality score was invented for primers the pipeline never scored"


def test_the_default_gate_value_is_also_quiet(primed, monkeypatch, caplog):
    """`parameter.min_amp_pred` defaults to 10.0, not None, on a real CLI run.

    Warning on that would fire on every ordinary invocation, which is how a
    useful warning becomes noise nobody reads.
    """
    from neoswga.core import parameter

    monkeypatch.setattr(parameter, "min_amp_pred", 10.0, raising=False)
    with caplog.at_level(logging.WARNING):
        _run(primed)

    assert "min_amp_pred" not in caplog.text


# ---------------------------------------------------------------------------
# The flag must actually reach the stage
# ---------------------------------------------------------------------------


def test_the_amp_model_flag_exists_on_the_score_subparser():
    """A capability with no CLI route is this repository's recurring defect."""
    from neoswga.cli_unified import create_parser

    parser = create_parser()
    score = [a for a in parser._subparsers._group_actions][0].choices["score"]
    dests = {a.dest for a in score._actions}

    assert "amp_model" in dests, f"--amp-model is not offered: {sorted(dests)}"


def test_the_flag_routes_to_the_parameter_module(tmp_path, monkeypatch):
    """Spy on the stage rather than trust the assignment."""
    import json

    import neoswga.cli.pipeline as cli_pipeline
    import neoswga.core.pipeline as pipeline_mod
    from neoswga.core import parameter

    (tmp_path / "params.json").write_text(
        json.dumps(
            {
                "schema_version": 2,
                "fg_genomes": ["fg.fna"],
                "fg_prefixes": ["fg"],
                "bg_genomes": [],
                "bg_prefixes": [],
                "data_dir": str(tmp_path),
                "polymerase": "phi29",
                "reaction_temp": 30.0,
                "min_k": 12,
                "max_k": 12,
                "min_fg_freq": 1e-5,
                "max_bg_freq": 5e-6,
                "min_tm": 15,
                "max_tm": 45,
                "max_gini": 0.6,
                "max_primer": 500,
                "cpus": 1,
                "fg_seq_lengths": [1_000_000],
            }
        )
    )

    seen = {}
    monkeypatch.setattr(
        pipeline_mod,
        "step3",
        lambda *a, **k: seen.update(use=getattr(parameter, "use_amp_model", None)),
    )
    monkeypatch.setattr(pipeline_mod, "_initialize", lambda: None)
    monkeypatch.setattr(cli_pipeline, "setup_gpu_acceleration", lambda *a, **k: None)
    monkeypatch.setattr(cli_pipeline, "report_unimplemented_options", lambda *a, **k: None)

    class _Args:
        json_file = str(tmp_path / "params.json")
        quiet = True
        seed = None
        enable_qa = False
        amp_model = True
        min_amp_pred = None
        full_score = False
        fast_score = False

    cli_pipeline.run_step3(_Args())
    assert seen.get("use") is True, "--amp-model did not reach parameter.use_amp_model"
