"""Fitting the coverage reach to observed depth rather than assuming it.

The reach decides both what coverage gets reported and which primers get
selected, and neither convention in the literature is measured. swga 2.0 uses
phi29's ~70 kb single-molecule processivity -- how far one molecule *can* be
extended, not how far a product reaches before a neighbour truncates it.
NeoSWGA's ~3 kb default comes from the inter-primer spacings published designs
chose, which is a designer's decision rather than an observation.

A BAM from a real SWGA run contains the answer: if products reach R bases,
depth should fall away from binding sites on a length scale of R.

The honest failure mode matters as much as the fit. Depth from a library with
no primer-position signal will still produce a best-scoring reach, because
something always scores highest. `fit_reach` reports the correlation and marks
the result uninformative below a floor, so a caller can tell a measurement from
an arbitrary maximum.
"""

import numpy as np
import pytest

pytest.importorskip("scipy")

from neoswga.core.reach_calibration import (
    DEFAULT_REACH_GRID,
    MIN_INFORMATIVE_CORRELATION,
    ReachFit,
    fit_reach,
    format_reach_table,
    predicted_depth,
)

GENOME = 300_000


def synthetic_depth(positions, reach, noise=0.0, seed=3):
    """Depth generated by a known reach, so the fit has a right answer."""
    profile = predicted_depth(positions, GENOME, reach)
    if noise:
        rng = np.random.default_rng(seed)
        profile = profile + rng.normal(0.0, noise * (profile.std() or 1.0), GENOME)
    return profile


# ----------------------------------------------------------------------
# The kernel
# ----------------------------------------------------------------------


def test_depth_tapers_away_from_a_binding_site():
    """A rectangular kernel would make every reach predict a flat profile once
    sites overlap, which removes the signal the fit runs on."""
    profile = predicted_depth([50_000], GENOME, 5000)

    assert profile[50_000] == pytest.approx(1.0)
    assert profile[52_500] == pytest.approx(0.5, abs=0.01)
    assert profile[56_000] == 0.0


def test_sites_accumulate():
    """Two nearby sites prime a region more than one does."""
    one = predicted_depth([50_000], GENOME, 5000)
    two = predicted_depth([50_000, 51_000], GENOME, 5000)

    assert two[50_500] > one[50_500]


def test_windows_are_clipped_at_the_sequence_ends():
    """A site near position 0 must not wrap or index out of bounds."""
    profile = predicted_depth([10, GENOME - 10], GENOME, 5000)

    assert len(profile) == GENOME
    assert profile[0] > 0
    assert profile[-1] > 0


# ----------------------------------------------------------------------
# The fit recovers a known reach
# ----------------------------------------------------------------------


@pytest.mark.parametrize("true_reach", [2000, 10000])
def test_it_recovers_the_reach_that_generated_the_depth(true_reach):
    """The property that makes this a measurement rather than a guess."""
    rng = np.random.default_rng(7)
    positions = sorted(rng.integers(0, GENOME, 60).tolist())
    depth = synthetic_depth(positions, true_reach)

    fit = fit_reach(depth, positions)

    assert fit.informative
    # Neighbouring grid points are within a factor of ~1.5 of each other, so
    # requiring the exact point would be testing grid resolution, not recovery.
    assert 0.5 * true_reach <= fit.best_reach <= 2.0 * true_reach, fit.by_reach


def test_it_survives_noise():
    rng = np.random.default_rng(9)
    positions = sorted(rng.integers(0, GENOME, 60).tolist())
    depth = synthetic_depth(positions, 5000, noise=0.5)

    fit = fit_reach(depth, positions)

    assert fit.informative
    assert 2000 <= fit.best_reach <= 15000, fit.by_reach


# ----------------------------------------------------------------------
# It says when it does not know
# ----------------------------------------------------------------------


def test_depth_unrelated_to_the_primers_is_reported_as_uninformative():
    """The failure that matters. Something always scores highest, so a bare
    argmax would return a confident-looking reach from a uniform library."""
    rng = np.random.default_rng(5)
    positions = sorted(rng.integers(0, GENOME, 60).tolist())
    depth = rng.normal(100.0, 10.0, GENOME)

    fit = fit_reach(depth, positions)

    assert not fit.informative
    assert fit.correlation < MIN_INFORMATIVE_CORRELATION
    assert "not evidence" in fit.note


def test_no_binding_sites_is_reported_rather_than_fitted():
    fit = fit_reach(np.ones(GENOME), [])

    assert not fit.informative
    assert fit.best_reach == 0
    assert "nothing to fit" in fit.note


def test_empty_depth_does_not_raise():
    fit = fit_reach(np.array([]), [10, 20])

    assert not fit.informative


def test_an_optimum_at_the_edge_of_the_grid_says_so():
    """A best value at the largest reach tried may be the edge rather than an
    optimum, and a user acting on it would pick a reach the data does not
    support."""
    rng = np.random.default_rng(13)
    positions = sorted(rng.integers(0, GENOME, 40).tolist())
    depth = synthetic_depth(positions, 70000)

    fit = fit_reach(depth, positions, reaches=[1000, 3000, 70000])

    if fit.best_reach == 70000:
        assert "may be higher" in fit.note


# ----------------------------------------------------------------------
# Reporting
# ----------------------------------------------------------------------


def test_the_table_shows_the_whole_grid_not_just_the_winner():
    """A flat optimum means the data cannot separate 3 kb from 20 kb, which is
    a different situation from a sharp one and must not be reported as the same
    number with the same confidence."""
    rng = np.random.default_rng(4)
    positions = sorted(rng.integers(0, GENOME, 50).tolist())
    fit = fit_reach(synthetic_depth(positions, 5000), positions)

    text = format_reach_table(fit)

    for reach in DEFAULT_REACH_GRID:
        assert f"{reach:,}" in text
    assert "best" in text
    assert "--coverage-reach" in text, "the table should say how to apply the result"


def test_an_uninformative_fit_does_not_suggest_applying_it():
    fit = ReachFit(
        best_reach=3000,
        correlation=0.01,
        by_reach={3000: 0.01},
        informative=False,
        contig="chr1",
        note="Best correlation 0.010 is below 0.15: not evidence.",
    )

    assert "--coverage-reach" not in format_reach_table(fit)


def test_it_serializes():
    fit = fit_reach(np.ones(GENOME), [])

    payload = fit.to_dict()
    assert set(payload) >= {"best_reach", "correlation", "informative", "note"}
    assert all(isinstance(k, str) for k in payload["by_reach"])
