#!/usr/bin/env python3
"""
Train enhanced random forest model with 120+ features.

Uses training data generated by generate_training_data.py to train
a random forest model using the advanced features from
advanced_features.py.

This replaces the basic 52-feature model with a 120+ feature model
that includes:
- Thermodynamic features with reaction conditions
- Secondary structure predictions
- Positional/spatial binding features
- Sequence complexity metrics
- K-mer motif frequencies
- Binding landscape analysis
- Context and interaction features

Usage:
    python scripts/train_enhanced_rf.py \
        --training-data training_data.csv \
        --output-model enhanced_rf_model.pkl \
        --target-variable mean_enrichment
"""

import argparse
import json
import logging
import os
import pickle
import sys
from pathlib import Path
from typing import List, Dict, Optional, Tuple

import numpy as np
import pandas as pd
from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor
from sklearn.model_selection import train_test_split, cross_val_score, GridSearchCV
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import mean_squared_error, r2_score, mean_absolute_error
from sklearn.feature_selection import SelectFromModel, mutual_info_regression
import warnings

warnings.filterwarnings('ignore')

logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(levelname)s - %(message)s'
)
logger = logging.getLogger(__name__)


# Features to exclude from training (identifiers, targets)
EXCLUDE_COLUMNS = [
    'primer', 'set_id', 'set_size', 'simulation_success',
    'mean_fg_amplification', 'mean_bg_amplification', 'mean_enrichment',
    'log_enrichment', 'quality_score', 'num_sets'
]

# Default hyperparameters for random forest
DEFAULT_RF_PARAMS = {
    'n_estimators': 200,
    'max_depth': 15,
    'min_samples_split': 5,
    'min_samples_leaf': 2,
    'max_features': 'sqrt',
    'n_jobs': -1,
    'random_state': 42
}


def load_training_data(path: str) -> Tuple[pd.DataFrame, List[str]]:
    """
    Load training data and identify feature columns.

    Args:
        path: Path to training data CSV

    Returns:
        (DataFrame, list of feature column names)
    """
    df = pd.read_csv(path)
    logger.info(f"Loaded {len(df)} samples with {len(df.columns)} columns")

    # Identify feature columns
    feature_cols = [c for c in df.columns if c not in EXCLUDE_COLUMNS]

    logger.info(f"Identified {len(feature_cols)} feature columns")

    return df, feature_cols


def prepare_features(df: pd.DataFrame, feature_cols: List[str],
                    target_col: str = 'log_enrichment') -> Tuple:
    """
    Prepare features and target for training.

    Args:
        df: Training DataFrame
        feature_cols: Feature column names
        target_col: Target variable column

    Returns:
        (X, y, feature_names)
    """
    # Remove rows with missing target
    df_clean = df.dropna(subset=[target_col])
    logger.info(f"After removing missing targets: {len(df_clean)} samples")

    # Extract features and target
    X = df_clean[feature_cols].copy()
    y = df_clean[target_col].copy()

    # Handle missing values in features
    for col in X.columns:
        if X[col].isna().any():
            # Fill with median for numeric columns
            X[col] = X[col].fillna(X[col].median())

    # Handle infinite values
    X = X.replace([np.inf, -np.inf], np.nan)
    X = X.fillna(0)

    logger.info(f"Final features shape: {X.shape}")
    logger.info(f"Target shape: {y.shape}")
    logger.info(f"Target range: [{y.min():.3f}, {y.max():.3f}]")

    return X, y, list(X.columns)


def select_important_features(X: pd.DataFrame, y: pd.Series,
                             n_features: int = 50) -> List[str]:
    """
    Select most important features using mutual information.

    Args:
        X: Feature DataFrame
        y: Target Series
        n_features: Number of features to select

    Returns:
        List of selected feature names
    """
    logger.info(f"Selecting top {n_features} features using mutual information...")

    # Calculate mutual information
    mi_scores = mutual_info_regression(X, y, random_state=42)

    # Create ranking
    feature_importance = pd.DataFrame({
        'feature': X.columns,
        'mi_score': mi_scores
    }).sort_values('mi_score', ascending=False)

    # Select top features
    selected = feature_importance.head(n_features)['feature'].tolist()

    logger.info("Top 10 features by mutual information:")
    for i, row in feature_importance.head(10).iterrows():
        logger.info(f"  {row['feature']}: {row['mi_score']:.4f}")

    return selected


def train_random_forest(X_train: pd.DataFrame, y_train: pd.Series,
                       params: Optional[Dict] = None,
                       tune_hyperparams: bool = False) -> RandomForestRegressor:
    """
    Train random forest regressor.

    Args:
        X_train: Training features
        y_train: Training target
        params: Model parameters
        tune_hyperparams: Whether to perform grid search

    Returns:
        Trained model
    """
    if params is None:
        params = DEFAULT_RF_PARAMS.copy()

    if tune_hyperparams:
        logger.info("Performing hyperparameter tuning...")

        param_grid = {
            'n_estimators': [100, 200, 300],
            'max_depth': [10, 15, 20, None],
            'min_samples_split': [2, 5, 10],
            'min_samples_leaf': [1, 2, 4]
        }

        rf = RandomForestRegressor(random_state=42, n_jobs=-1)
        grid_search = GridSearchCV(
            rf, param_grid, cv=5, scoring='r2', n_jobs=-1, verbose=1
        )
        grid_search.fit(X_train, y_train)

        logger.info(f"Best parameters: {grid_search.best_params_}")
        logger.info(f"Best CV score: {grid_search.best_score_:.4f}")

        return grid_search.best_estimator_

    else:
        logger.info("Training random forest with default parameters...")
        rf = RandomForestRegressor(**params)
        rf.fit(X_train, y_train)
        return rf


def evaluate_model(model, X_test: pd.DataFrame, y_test: pd.Series,
                  feature_names: List[str]) -> Dict:
    """
    Evaluate model performance.

    Args:
        model: Trained model
        X_test: Test features
        y_test: Test target
        feature_names: Feature names

    Returns:
        Evaluation metrics
    """
    y_pred = model.predict(X_test)

    metrics = {
        'r2': r2_score(y_test, y_pred),
        'rmse': np.sqrt(mean_squared_error(y_test, y_pred)),
        'mae': mean_absolute_error(y_test, y_pred),
        'correlation': np.corrcoef(y_test, y_pred)[0, 1]
    }

    logger.info("Model Performance:")
    logger.info(f"  R-squared: {metrics['r2']:.4f}")
    logger.info(f"  RMSE: {metrics['rmse']:.4f}")
    logger.info(f"  MAE: {metrics['mae']:.4f}")
    logger.info(f"  Correlation: {metrics['correlation']:.4f}")

    # Feature importance
    if hasattr(model, 'feature_importances_'):
        importance = pd.DataFrame({
            'feature': feature_names,
            'importance': model.feature_importances_
        }).sort_values('importance', ascending=False)

        logger.info("\nTop 15 Most Important Features:")
        for i, row in importance.head(15).iterrows():
            logger.info(f"  {row['feature']}: {row['importance']:.4f}")

        metrics['feature_importance'] = importance.to_dict('records')

    return metrics


def save_model(model, feature_names: List[str], metrics: Dict,
              output_path: str, metadata: Optional[Dict] = None):
    """
    Save trained model with metadata.

    Args:
        model: Trained model
        feature_names: Feature names used in training
        metrics: Evaluation metrics
        output_path: Output pickle path
        metadata: Additional metadata
    """
    save_data = {
        'model': model,
        'feature_names': feature_names,
        'metrics': metrics,
        'metadata': metadata or {},
        'model_type': 'enhanced_random_forest',
        'version': '2.0'
    }

    with open(output_path, 'wb') as f:
        pickle.dump(save_data, f)

    logger.info(f"Model saved to {output_path}")


def cross_validate_model(model, X: pd.DataFrame, y: pd.Series,
                        cv: int = 5) -> Dict:
    """
    Perform cross-validation.

    Args:
        model: Model to evaluate
        X: Features
        y: Target
        cv: Number of folds

    Returns:
        CV metrics
    """
    logger.info(f"Performing {cv}-fold cross-validation...")

    r2_scores = cross_val_score(model, X, y, cv=cv, scoring='r2')
    neg_mse_scores = cross_val_score(model, X, y, cv=cv, scoring='neg_mean_squared_error')

    rmse_scores = np.sqrt(-neg_mse_scores)

    logger.info(f"  R-squared: {r2_scores.mean():.4f} (+/- {r2_scores.std():.4f})")
    logger.info(f"  RMSE: {rmse_scores.mean():.4f} (+/- {rmse_scores.std():.4f})")

    return {
        'cv_r2_mean': r2_scores.mean(),
        'cv_r2_std': r2_scores.std(),
        'cv_rmse_mean': rmse_scores.mean(),
        'cv_rmse_std': rmse_scores.std(),
        'cv_r2_scores': r2_scores.tolist(),
        'cv_rmse_scores': rmse_scores.tolist()
    }


def main():
    parser = argparse.ArgumentParser(
        description='Train enhanced random forest model with 120+ features'
    )

    parser.add_argument('--training-data', required=True,
                       help='Path to training data CSV')
    parser.add_argument('--output-model', default='enhanced_rf_model.pkl',
                       help='Output model path')
    parser.add_argument('--target-variable', default='log_enrichment',
                       choices=['log_enrichment', 'mean_enrichment', 'quality_score'],
                       help='Target variable to predict')
    parser.add_argument('--n-features', type=int, default=None,
                       help='Number of features to select (None = all)')
    parser.add_argument('--tune-hyperparams', action='store_true',
                       help='Perform hyperparameter tuning')
    parser.add_argument('--test-size', type=float, default=0.2,
                       help='Test set fraction')
    parser.add_argument('--cross-validate', action='store_true',
                       help='Perform cross-validation')
    parser.add_argument('--output-features', default=None,
                       help='Path to save feature list JSON')

    args = parser.parse_args()

    # Load data
    df, feature_cols = load_training_data(args.training_data)

    # Prepare features
    X, y, feature_names = prepare_features(df, feature_cols, args.target_variable)

    # Feature selection
    if args.n_features is not None and args.n_features < len(feature_names):
        selected_features = select_important_features(X, y, args.n_features)
        X = X[selected_features]
        feature_names = selected_features
        logger.info(f"Using {len(feature_names)} selected features")

    # Split data
    X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=args.test_size, random_state=42
    )
    logger.info(f"Train set: {len(X_train)}, Test set: {len(X_test)}")

    # Train model
    model = train_random_forest(
        X_train, y_train,
        tune_hyperparams=args.tune_hyperparams
    )

    # Evaluate
    metrics = evaluate_model(model, X_test, y_test, feature_names)

    # Cross-validation
    if args.cross_validate:
        cv_metrics = cross_validate_model(
            RandomForestRegressor(**DEFAULT_RF_PARAMS),
            X, y
        )
        metrics.update(cv_metrics)

    # Save model
    metadata = {
        'training_data': args.training_data,
        'target_variable': args.target_variable,
        'n_samples': len(X),
        'n_features': len(feature_names),
        'test_size': args.test_size
    }

    save_model(model, feature_names, metrics, args.output_model, metadata)

    # Save feature list
    if args.output_features:
        with open(args.output_features, 'w') as f:
            json.dump({
                'features': feature_names,
                'importance': metrics.get('feature_importance', [])
            }, f, indent=2)
        logger.info(f"Feature list saved to {args.output_features}")

    logger.info("Training complete!")


if __name__ == '__main__':
    main()
