"""
Random forest preprocessing for primer scoring.

This module provides feature engineering and model prediction for primer scoring.
Supports two modes:
1. Standard mode (52 features): Uses original thermodynamic histogram features
2. Enhanced mode (120+ features): Uses advanced feature engineering with
   thermodynamics, secondary structure, spatial, and complexity features

Enhanced features are generated by advanced_features.py and trained models
can be generated using scripts/train_enhanced_rf.py.

Performance optimizations (v3.0):
- K-mer file caching: Files loaded once per step, not per primer
- Thermodynamic caching: LRU cache in thermodynamics.py for 10-100x speedup
- Vectorized binning: numpy operations instead of per-kmer digitize
"""

import neoswga.core.utility
import pandas as pd
from functools import partial
import neoswga.core.parameter as parameter
import numpy as np
import pickle
import hashlib
import melting
import os
import sys
from bisect import bisect_right
from neoswga.core.kmer_counter import get_kmer_to_count_dict
import sklearn
import sklearn.ensemble
import warnings
import logging
from typing import Dict, List, Optional, Tuple

# =============================================================================
# Secure Model Loading
# =============================================================================

# Known SHA-256 hashes of trusted model files
# Update these when retraining models
_TRUSTED_MODEL_HASHES = {
    'random_forest_filter.p': '7320e265744b4449353e404f7f0240f3918026a31d619d2c235a422c12c54e76',
}

# Set to False to disable hash verification (not recommended for production)
_VERIFY_MODEL_HASHES = True


class ModelIntegrityError(Exception):
    """Raised when model file hash verification fails."""
    pass


def _compute_file_hash(filepath: str) -> str:
    """Compute SHA-256 hash of a file."""
    sha256_hash = hashlib.sha256()
    with open(filepath, "rb") as f:
        for chunk in iter(lambda: f.read(8192), b""):
            sha256_hash.update(chunk)
    return sha256_hash.hexdigest()


def load_model_safely(model_path: str, verify_hash: bool = None) -> object:
    """
    Load a pickle model file with optional hash verification.

    This function provides protection against pickle deserialization attacks
    by verifying the model file hash before loading.

    Args:
        model_path: Path to the model file.
        verify_hash: Whether to verify hash. Defaults to _VERIFY_MODEL_HASHES.

    Returns:
        The unpickled model object.

    Raises:
        FileNotFoundError: If model file doesn't exist.
        ModelIntegrityError: If hash verification fails.
    """
    if verify_hash is None:
        verify_hash = _VERIFY_MODEL_HASHES

    if not os.path.exists(model_path):
        raise FileNotFoundError(f"Model file not found: {model_path}")

    model_name = os.path.basename(model_path)

    if verify_hash and model_name in _TRUSTED_MODEL_HASHES:
        expected_hash = _TRUSTED_MODEL_HASHES[model_name]
        actual_hash = _compute_file_hash(model_path)

        if actual_hash != expected_hash:
            raise ModelIntegrityError(
                f"Model file hash mismatch for {model_name}.\n"
                f"Expected: {expected_hash}\n"
                f"Actual:   {actual_hash}\n"
                f"The model file may have been corrupted or tampered with.\n"
                f"To update the hash after retraining, update _TRUSTED_MODEL_HASHES "
                f"in rf_preprocessing.py"
            )
        logging.getLogger(__name__).debug(
            f"Model hash verified: {model_name}"
        )
    elif verify_hash:
        logging.getLogger(__name__).warning(
            f"No trusted hash for model: {model_name}. Loading without verification."
        )

    with open(model_path, 'rb') as f:
        return pickle.load(f)


# Module-level k-mer cache for performance
# Structure: {(fname_prefix, k): {kmer: count}}
_kmer_cache: Dict[Tuple[str, int], Dict[str, int]] = {}

# Worker-shared data (populated by initializer, shared via fork)
_worker_fnames: List[str] = []
_worker_k: int = 0


def _init_kmer_worker(fnames: List[str], k: int, sampling_enabled: bool = False,
                      sample_rate: float = 0.1, min_count_threshold: int = 5) -> None:
    """
    Worker initializer to preload k-mer files and set sampling parameters.

    This function runs once when each worker starts, loading k-mer data
    into the module-level cache and setting sampling parameters. This eliminates
    redundant file loading since each worker loads files only once instead of per-primer.

    Expected speedup: 35-45% for Step 3 scoring (more with sampling enabled).

    Args:
        fnames: List of file prefixes for k-mer files
        k: K-mer length to load
        sampling_enabled: Whether k-mer sampling is enabled
        sample_rate: Fraction of k-mers to sample (0.01-1.0)
        min_count_threshold: Always include k-mers with count >= this
    """
    global _kmer_cache, _worker_fnames, _worker_k
    global _sampling_enabled, _sample_rate, _min_count_threshold

    _worker_fnames = fnames
    _worker_k = k

    # Set sampling parameters in worker
    _sampling_enabled = sampling_enabled
    _sample_rate = sample_rate
    _min_count_threshold = min_count_threshold

    # Preload k-mer files into cache for this worker
    for fname_prefix in fnames:
        cache_key = (fname_prefix, k)
        if cache_key not in _kmer_cache:
            fpath = f"{fname_prefix}_{k}mer_all.txt"
            if os.path.exists(fpath):
                _kmer_cache[cache_key] = get_kmer_to_count_dict(fpath)
                logger.debug(f"Worker loaded {fpath}: {len(_kmer_cache[cache_key]):,} k-mers")
            else:
                _kmer_cache[cache_key] = {}
                logger.warning(f"K-mer file not found: {fpath}")

# Fix for sklearn >= 1.0 compatibility with models pickled on older versions
# Several internal modules were renamed with underscore prefix in sklearn 1.0
def _fix_sklearn_module_aliases():
    """Add module aliases for sklearn modules renamed in version 1.0+."""
    module_mappings = [
        ('sklearn.ensemble.forest', 'sklearn.ensemble._forest'),
        ('sklearn.ensemble.weight_boosting', 'sklearn.ensemble._weight_boosting'),
        ('sklearn.tree.tree', 'sklearn.tree._classes'),
        ('sklearn.neighbors.typedefs', 'sklearn.neighbors._typedefs'),
        ('sklearn.utils.weight_vector', 'sklearn.utils._weight_vector'),
    ]
    for old_name, new_name in module_mappings:
        try:
            # Import the new module location
            parts = new_name.split('.')
            mod = __import__(new_name)
            for part in parts[1:]:
                mod = getattr(mod, part)
            sys.modules[old_name] = mod
        except (ImportError, AttributeError):
            pass  # Module not available or already exists

_fix_sklearn_module_aliases()

# Use new thermodynamics module (replaces deprecated thermo_estimation)
import neoswga.core.thermodynamics as thermo

logger = logging.getLogger(__name__)

# Names of the features not including the thermodynamic features
base_features = ['molarity', 'sequence.length', 'number.of.A', 'proportion.of.A', 'number.of.T', 'proportion.of.T', 'number.of.G', 'proportion.of.G', 'number.of.C', 'proportion.of.C', 'GC.content', 'melting_tm', 'GC.clamp', 'longest.A.repeat', 'longest.T.repeat', 'longest.G.repeat', 'longest.C.repeat', 'AA repeat', 'CC repeat', 'TT repeat', 'GG repeat', '3.end.first.base', '3.end.second.base', '3.end.third.base', '3.end.fourth.base', '3.end.fifth.base']

# =============================================================================
# Thermodynamic Delta-G Histogram Bins
# =============================================================================
# These bins define the histogram edges for binning predicted delta-G (free energy)
# values of primer-template binding. The bins span -20 to +3 kcal/mol:
#   - Strong binding: < -10 kcal/mol (favorable)
#   - Moderate binding: -10 to -5 kcal/mol
#   - Weak binding: -5 to 0 kcal/mol
#   - Unfavorable: > 0 kcal/mol
# Finer resolution (0.5 kcal/mol steps) in the -6 to +3 range captures
# the critical transition zone where binding strength varies significantly.
DELTA_G_HISTOGRAM_BINS = [
    -20, -18, -16, -14, -12, -10,  # Coarse bins for strong binding
    -9, -8, -7, -6,                 # Moderate binding
    -5.5, -5, -4.5, -4, -3.5, -3,  # Fine resolution transition zone
    -2.5, -2, -1.5, -1, -0.5,      # Weak binding
    0, 0.5, 1, 1.5, 2, 2.5, 3      # Unfavorable binding
]

# Backward-compatible alias
bins = DELTA_G_HISTOGRAM_BINS
histogram_upper_bound = DELTA_G_HISTOGRAM_BINS[-1]  # +3 kcal/mol
histogram_lower_bound = DELTA_G_HISTOGRAM_BINS[0]   # -20 kcal/mol
features = list(base_features)
delta_g_on_features = ['on_target_' + str(bin) for bin in bins[1:]]

# List of all features in the regression
regression_features = features + delta_g_on_features

def get_features(primer, target=None, molarity=2.5):
    """
    Function called by create_base_feature_matrix pool and used to make feature vector for each primer.

    Args:
        primer: The primer for which to make the feature vector for.
        target: Boolean variable--true if the primer exists in the on-target genome (dropped in the regression).
        molarity: The molarity of the plasmid experiment concentration.

    Returns:
        result: A list of all the base feature values, the primer sequence, and whether it is in the on-target genome.
    """
    feature_dict = {}
    feature_dict['molarity'] = molarity
    feature_dict['sequence.length'] = len(primer)

    feature_dict['number.of.A'] = primer.count('A')
    feature_dict['number.of.G'] = primer.count('G')
    feature_dict['number.of.T'] = primer.count('T')
    feature_dict['number.of.C'] = primer.count('C')

    feature_dict['proportion.of.A'] = feature_dict['number.of.A']/feature_dict['sequence.length']
    feature_dict['proportion.of.G'] = feature_dict['number.of.G'] / feature_dict['sequence.length']
    feature_dict['proportion.of.T'] = feature_dict['number.of.T'] / feature_dict['sequence.length']
    feature_dict['proportion.of.C'] = feature_dict['number.of.C'] / feature_dict['sequence.length']

    feature_dict['GC.content'] = (feature_dict['number.of.G'] + feature_dict['number.of.C'])/ feature_dict['sequence.length']

    feature_dict['longest.A.repeat'] =  neoswga.core.utility.longest_char_repeat(primer,'A')
    feature_dict['longest.G.repeat'] =  neoswga.core.utility.longest_char_repeat(primer, 'G')
    feature_dict['longest.T.repeat'] =  neoswga.core.utility.longest_char_repeat(primer, 'T')
    feature_dict['longest.C.repeat'] =  neoswga.core.utility.longest_char_repeat(primer, 'C')

    feature_dict['AA repeat'] = primer.count('AA')
    feature_dict['GG repeat'] = primer.count('GG')
    feature_dict['CC repeat'] = primer.count('CC')
    feature_dict['TT repeat'] = primer.count('TT')

    feature_dict['target'] = target

    feature_dict['melting_tm'] = melting.temp(primer)
    # GC clamp: count G and C in the last 5 bases (3' end)
    last_five_end = primer[-5:]  # Fixed: was primer[:-5] which excluded last 5
    feature_dict['GC.clamp'] = last_five_end.count('C') + last_five_end.count('G')

    feature_dict['3.end.first.base'] =  neoswga.core.utility.char_to_int_dict[primer[-1]]
    feature_dict['3.end.second.base'] =  neoswga.core.utility.char_to_int_dict[primer[-2]]
    feature_dict['3.end.third.base'] =  neoswga.core.utility.char_to_int_dict[primer[-3]]
    feature_dict['3.end.fourth.base'] =  neoswga.core.utility.char_to_int_dict[primer[-4]]
    feature_dict['3.end.fifth.base'] =  neoswga.core.utility.char_to_int_dict[primer[-5]]

    result = [primer, target]
    for feature in base_features:
        result.append(feature_dict[feature])
    return result

def create_base_feature_matrix(primer_list, molarity):
    """
    Creates the feature matrix, not including the delta_G features.

    Args:
        primer_list: The list of primers to create the feature matrix for.
        molarity: The molarity of the plasmid experiment experiments.

    Returns:
        df: The pandas dataframe including the features for the base regression features, the sequence of the primer,
        and whether it exists in the target genome (where the last two features are dropped in regression).
    """
    get_features_partial = partial(get_features, molarity = molarity)
    results =  neoswga.core.utility.create_pool(get_features_partial, primer_list, parameter.cpus)
    f = ['sequence','target']
    f.extend(base_features)
    df = pd.DataFrame(results, columns=f)
    return df

def get_all_predicted_delta_G_for_all_files_transformed(primer_list, target, fnames, f_out_name=None):
    """
    Gets all the predicted thermodynamic values for all the candidate primers (primer_list) in all the genome files.

    Performance optimization: Uses pool initializer to preload k-mer files once per worker
    instead of per-primer, providing 35-45% speedup.

    Args:
        primer_list: The list of candidate primers which we are evaluating.
        target: Boolean variable--true if the primer exists in the on-target genome (dropped in the regression).
        fnames: A list of the paths to the genome files.
        f_out_name: If this is not None, this saves the feature matrix using this as the file path.

    Returns:
        df: A pandas dataframe representing the feature matrix of the basic features (defined at the top) for the
        primers in primer_list.

    """
    # Handle empty primer list (works for both list and pandas Series)
    if len(primer_list) == 0:
        return pd.DataFrame()

    # Determine k from primer list (assumes uniform length in batch)
    # Use iloc[0] for pandas Series compatibility
    first_primer = primer_list.iloc[0] if hasattr(primer_list, 'iloc') else primer_list[0]
    k = len(first_primer)

    seq_initialized_f = partial(get_all_predicted_delta_G_per_primer_transformed, fnames=fnames)

    # Use pool with initializer to preload k-mer files once per worker
    # This eliminates redundant file I/O (8 workers loading same files = 8x overhead)
    # Also passes sampling parameters to ensure they're set in worker processes
    sampling_msg = ""
    if _sampling_enabled:
        sampling_msg = f" (sampling {_sample_rate*100:.0f}%)"
    logger.info(f"Scoring {len(primer_list)} primers ({k}bp) using {parameter.cpus} workers{sampling_msg}...")
    arr_transformed = neoswga.core.utility.create_pool_with_progress(
        seq_initialized_f,
        primer_list,
        parameter.cpus,
        desc=f"Scoring {k}bp primers",
        initializer=_init_kmer_worker,
        initargs=(fnames, k, _sampling_enabled, _sample_rate, _min_count_threshold)
    )

    if target:
        columns = ["on_target_" + str(i) for i in bins[1:]]
    else:
        columns = ["off_target_" + str(i) for i in bins[1:]]

    df = pd.DataFrame(arr_transformed, columns=columns)

    if f_out_name:
        with open(f_out_name, "wb") as fh:
            pickle.dump(df, fh)

    return df

def get_cached_kmer_dict(fname_prefix: str, k: int) -> Dict[str, int]:
    """
    Get k-mer count dictionary with caching.

    Loads k-mer file once and caches for subsequent calls.
    This provides 10-100x speedup for Step 3 by avoiding repeated file I/O.

    Args:
        fname_prefix: Path prefix for k-mer files
        k: K-mer length

    Returns:
        Dictionary mapping k-mer sequence to count
    """
    cache_key = (fname_prefix, k)
    if cache_key not in _kmer_cache:
        fpath = f"{fname_prefix}_{k}mer_all.txt"
        if os.path.exists(fpath):
            _kmer_cache[cache_key] = get_kmer_to_count_dict(fpath)
        else:
            _kmer_cache[cache_key] = {}
    return _kmer_cache[cache_key]


def preload_kmer_files(fnames: List[str], k_values: List[int]) -> None:
    """
    Preload k-mer files into cache for a set of k values.

    Call this before processing primers to ensure all files are loaded once.

    Args:
        fnames: List of file prefixes
        k_values: List of k-mer lengths to load
    """
    for fname_prefix in fnames:
        for k in k_values:
            get_cached_kmer_dict(fname_prefix, k)
    logger.info(f"Preloaded {len(_kmer_cache)} k-mer files into cache")


def clear_kmer_cache() -> None:
    """Clear the k-mer file cache to free memory."""
    global _kmer_cache
    _kmer_cache = {}


# Module-level sampling parameters (can be set via parameter module)
# Sampling enabled by default for 10x speedup with <5% accuracy loss
_sampling_enabled: bool = True
_sample_rate: float = 0.1  # Sample 10% of k-mers by default
_min_count_threshold: int = 5  # Always include k-mers with count >= threshold


def enable_kmer_sampling(sample_rate: float = 0.1, min_count: int = 5) -> None:
    """
    Enable k-mer sampling for faster scoring.

    Sampling reduces computation from O(primers * k-mers) to O(primers * sampled_k-mers),
    providing 10-100x speedup with 5-10% accuracy loss.

    Args:
        sample_rate: Fraction of k-mers to sample (0.01-1.0). Default 0.1 = 10%
        min_count: Always include k-mers with count >= this threshold
    """
    global _sampling_enabled, _sample_rate, _min_count_threshold
    _sampling_enabled = True
    _sample_rate = max(0.01, min(1.0, sample_rate))
    _min_count_threshold = max(1, min_count)
    logger.info(f"K-mer sampling enabled: rate={_sample_rate}, min_count={_min_count_threshold}")


def disable_kmer_sampling() -> None:
    """Disable k-mer sampling (use all k-mers)."""
    global _sampling_enabled
    _sampling_enabled = False
    logger.info("K-mer sampling disabled")


def get_all_predicted_delta_G_per_primer_transformed(primer, fnames=None, penalty=4):
    """
    Compute binned thermodynamic values for primer-kmer binding.

    This function takes a primer and computes a vector of the binned thermodynamic values. It takes account both the
    forward and the reverse strand. For computing potential binding to k-mers in the forward strand, we want the
    thermodynamic values between the k-mer in the genome written 5' to 3' and the primer (written 3' to 5').
    For computing potential binding to k-mers in the reverse strand, we want the thermodynamic values between
    the primer and the complement of the k-mer in the genome.

    Performance optimizations:
    - Uses cached k-mer dictionaries (avoids repeated file I/O)
    - Uses cached thermodynamic calculations (LRU cache in thermodynamics.py)
    - Pre-computes primer transformations once
    - SAMPLING MODE: When enabled, samples k-mers for 10-100x speedup

    Args:
        primer: The primer for which to compute the predicted thermodynamic values.
        fnames: A list of the genomes to search and compute the predicted thermodynamic values binding with the primer.
        penalty: A value to add to the thermodynamic sum if a pair does not exist in Santa-Lucia's table.
        This usually means everything is a mismatch and it makes the binding much less likely.

    Returns:
        all_delta_G_vals: Vector of the histogram frequencies from -20 to 3 of the thermodynamic values resulting
        between the primer and all possible kmers in the genome files.
    """
    import random
    k = len(primer)

    # Pre-compute primer transformations once (instead of per k-mer)
    primer_reversed = neoswga.core.utility.reverse(primer)

    # Initialize histogram bins
    all_delta_G_vals = np.zeros(len(bins) - 1, dtype=np.int64)
    num_bins = len(bins) - 1

    for fname_prefix in fnames:
        # Use cached k-mer dictionary
        kmer_dict = get_cached_kmer_dict(fname_prefix, k)

        if not kmer_dict:
            continue

        # Calculate scale factor for sampling (to extrapolate histogram)
        scale_factor = 1.0
        if _sampling_enabled:
            scale_factor = 1.0 / _sample_rate

        # Pre-compute all k-mer complements before inner loop
        kmer_complements = {
            kmer_i: neoswga.core.utility.complement(kmer_i)
            for kmer_i in kmer_dict
        }

        # Process k-mers (with optional sampling)
        for kmer_i, count in kmer_dict.items():
            # SAMPLING: Skip low-frequency k-mers probabilistically
            if _sampling_enabled:
                # Always include high-count k-mers (they contribute most to binding)
                if count < _min_count_threshold:
                    # Sample low-count k-mers probabilistically
                    if random.random() > _sample_rate:
                        continue

            # Forward strand binding
            delta_G_val_forward = thermo.compute_free_energy_for_two_strings(
                kmer_i, primer_reversed, penalty
            )

            # Reverse strand binding (pre-computed complement of k-mer)
            delta_G_val_reverse = thermo.compute_free_energy_for_two_strings(
                primer, kmer_complements[kmer_i], penalty
            )

            # Effective count (scaled if sampling)
            effective_count = count
            if _sampling_enabled and count < _min_count_threshold:
                effective_count = int(count * scale_factor)

            # Bin forward value (bisect_right is faster than np.searchsorted
            # for the small non-uniform bin array)
            if delta_G_val_forward <= histogram_upper_bound:
                idx = bisect_right(bins, delta_G_val_forward) - 1
                if idx < 0:
                    idx = 0
                elif idx >= num_bins:
                    idx = num_bins - 1
                all_delta_G_vals[idx] += effective_count

            # Bin reverse value
            if delta_G_val_reverse <= histogram_upper_bound:
                idx = bisect_right(bins, delta_G_val_reverse) - 1
                if idx < 0:
                    idx = 0
                elif idx >= num_bins:
                    idx = num_bins - 1
                all_delta_G_vals[idx] += effective_count

    return all_delta_G_vals.tolist()

def create_augmented_df(fg_fnames, primer_list=None, feature_matrix=None, delta_G_matrix=None, molarity=None):
    """
    Creates the feature matrix including the thermodynamic features.

    Args:
        fg_fnames: A list of paths to the genome files.
        primer_list: The list of primers to create the feature matrix for. If None the feature_matrix cannot be None.
        feature_matrix: The feature matrix of the base features built using the above function create_base_feature_matrix.
        delta_G_matrix: A matrix containing the histogram frequences of the thermodynamic features, assuming it was
        computed already.
        molarity: The molarity of the plasmid experiment experiments.

    Returns:
        df: The pandas dataframe of the regression features (including the thermodynamic features),
        the sequence of the primer, and whether it exists in the target genome (where the last two features are
        dropped in regression).
    """
    if feature_matrix is None:
        logger.debug("feature matrix was none, creating base feature matrix")
        feature_matrix = create_base_feature_matrix(primer_list, molarity=molarity)
    feature_matrix = feature_matrix.reset_index()
    if delta_G_matrix is None:
        logger.debug("delta G matrix was none, computing thermodynamic features")
        if primer_list is None:
            primer_list = feature_matrix['sequence']

        delta_G_matrix = get_all_predicted_delta_G_for_all_files_transformed(primer_list, True, fg_fnames)
        logger.debug("Done computing foreground delta G features")

    df = pd.concat([feature_matrix, delta_G_matrix], axis=1)
    return df

def scale_delta_Gs(df_pred, on_scale=4000):
    """
    This scales the histogram frequencies of the thermodynamic values. This is necessary because often the off-target
    genome is much larger than the on-target genome. Using the ratio of the on-target length to off-target length as
    the on_scale is recommended.

    Args:
        df_pred: The dataframe containing the histogram frequencies of the thermodynamic values.
        on_scale: The value by which to normalize each value.

    Returns:
        df_pred: The rescaled dataframe.

    """
    df_pred[delta_g_on_features] = df_pred[delta_g_on_features]/(on_scale)
    return df_pred

def _heuristic_primer_score(row):
    """
    Calculate a heuristic-based primer amplification score when the ML model is unavailable.

    This fallback scoring function uses thermodynamic and sequence-based features
    to estimate amplification potential without requiring the trained random forest model.

    The score is based on:
    - Melting temperature (optimal 25-35C for MDA, 40-50C for EquiPhi29)
    - GC content (optimal 40-60%)
    - 3' end stability (G/C at 3' end is favorable)
    - Thermodynamic binding energy histogram (low delta-G bins indicate strong binding)

    Returns a score in the range [0, 20] to match the typical RF model output range.
    """
    score = 10.0  # baseline

    # Melting temperature contribution (optimal range 25-45C)
    tm = row.get('melting_tm', 30.0)
    if 30 <= tm <= 42:
        score += 2.0  # optimal range
    elif 25 <= tm < 30 or 42 < tm <= 50:
        score += 1.0  # acceptable range
    else:
        score -= 2.0  # suboptimal

    # GC content contribution (optimal 40-60%)
    gc = row.get('GC.content', 0.5)
    if 0.4 <= gc <= 0.6:
        score += 2.0
    elif 0.3 <= gc < 0.4 or 0.6 < gc <= 0.7:
        score += 1.0
    else:
        score -= 1.0

    # 3' end stability (G or C at 3' end)
    end_base = row.get('3.end.first.base', 0)
    if end_base in [2, 3]:  # G or C (encoded as 2 or 3)
        score += 1.0

    # GC clamp contribution
    gc_clamp = row.get('GC.clamp', 0)
    if 1 <= gc_clamp <= 3:
        score += 1.0
    elif gc_clamp > 4:
        score -= 0.5  # too strong clamp

    # Repeat penalty (long homopolymers are bad)
    max_repeat = max(
        row.get('longest.A.repeat', 0),
        row.get('longest.T.repeat', 0),
        row.get('longest.G.repeat', 0),
        row.get('longest.C.repeat', 0)
    )
    if max_repeat >= 4:
        score -= 2.0
    elif max_repeat >= 3:
        score -= 1.0

    # Thermodynamic binding features - favor strong binding (low delta-G)
    # Sum the low-energy bins (strong binding sites)
    strong_binding = 0
    for feat in delta_g_on_features[:10]:  # First 10 bins are lowest energy (strongest binding)
        strong_binding += row.get(feat, 0)

    # Normalize by total binding and add to score
    total_binding = sum(row.get(feat, 0) for feat in delta_g_on_features)
    if total_binding > 0:
        strong_ratio = strong_binding / total_binding
        score += strong_ratio * 3.0  # Up to +3 for strong binding

    # Clamp to reasonable range
    return max(0.0, min(20.0, score))


def predict_new_primers(df):
    """
    Runs the random forest regression on the input features to predict amplification scores.

    Falls back to a heuristic-based scoring function if the ML model cannot be loaded
    (e.g., due to sklearn version incompatibility or hash verification failure).

    Args:
        df: The input features.

    Returns:
        output_df: The predicted amplification scores.

    """
    warnings.filterwarnings('ignore')

    X_test = df[regression_features].copy()
    nan_cols = X_test.columns[X_test.isna().any()].tolist()
    if nan_cols:
        logger.warning(
            f"NaN values in {len(nan_cols)} feature columns: {nan_cols[:5]}. "
            "Filling with column medians."
        )
        for col in nan_cols:
            X_test[col] = X_test[col].fillna(X_test[col].median())
        # Drop any columns that are entirely NaN (median would also be NaN)
        still_nan = X_test.columns[X_test.isna().any()].tolist()
        if still_nan:
            logger.warning(f"Dropping {len(still_nan)} all-NaN columns: {still_nan}")
            X_test = X_test.drop(columns=still_nan)

    # Use __file__ to find model relative to this module
    model_dir = os.path.join(os.path.dirname(__file__), 'models')
    model_path = os.path.join(model_dir, 'random_forest_filter.p')

    try:
        # SECURE: Use load_model_safely with hash verification
        clf = load_model_safely(model_path)
        y_pred = clf.predict(X_test)
        logger.debug("Using trained random forest model for primer scoring")
    except ModelIntegrityError as e:
        # Model file has been tampered with - log and fall back
        logger.error(f"Model integrity check failed: {e}")
        logger.warning("Using heuristic-based scoring as fallback.")
        # Apply heuristic scoring to each row
        y_pred = df.apply(_heuristic_primer_score, axis=1).values
    except Exception as e:
        # Fallback to heuristic scoring when model fails to load
        # This can happen with sklearn version incompatibility
        logger.warning(f"Random forest model loading failed: {e}")
        logger.warning("Using heuristic-based scoring as fallback. "
                      "To use ML scoring, retrain model with current sklearn version.")
        # Apply heuristic scoring to each row
        y_pred = df.apply(_heuristic_primer_score, axis=1).values

    output_df = pd.DataFrame(y_pred, columns=['on.target.pred'])
    output_df = pd.concat([output_df, df], axis=1)
    return output_df

# ============================================================
# Enhanced Feature Engineering Support (120+ features)
# ============================================================

def predict_with_enhanced_features(primer_list, fg_genome_sequence, conditions=None,
                                   primer_positions=None, model_path=None):
    """
    Predict primer scores using enhanced 120+ feature model.

    Uses advanced feature engineering including thermodynamics with
    reaction conditions, secondary structure, spatial features,
    sequence complexity, and binding landscape analysis.

    Args:
        primer_list: List of primer sequences
        fg_genome_sequence: Target genome sequence string
        conditions: ReactionConditions object (or use defaults)
        primer_positions: Optional dict of {primer: {'forward': [...], 'reverse': [...]}}
        model_path: Path to enhanced model file (or use default)

    Returns:
        DataFrame with predictions and features
    """
    # Import advanced features module
    from neoswga.core.advanced_features import AdvancedFeatureEngineer
    from neoswga.core.reaction_conditions import ReactionConditions

    if conditions is None:
        conditions = ReactionConditions(temp=30.0, na_conc=50.0)

    # Engineer features
    logger.info(f"Engineering enhanced features for {len(primer_list)} primers...")
    feature_engineer = AdvancedFeatureEngineer(
        fg_genome_sequence, conditions, primer_positions or {}
    )
    features_df = feature_engineer.engineer_features(primer_list)
    logger.info(f"Generated {len(features_df.columns)} features")

    # Load enhanced model
    if model_path is None:
        model_dir = os.path.join(os.path.dirname(__file__), 'models')
        model_path = os.path.join(model_dir, 'enhanced_rf_model.pkl')

    if not os.path.exists(model_path):
        logger.warning(f"Enhanced model not found at {model_path}")
        logger.warning("Falling back to standard model. Run scripts/train_enhanced_rf.py first.")
        return None

    # Load model and feature list
    # SECURE: Use load_model_safely with hash verification
    try:
        model_data = load_model_safely(model_path, verify_hash=False)  # Enhanced models may vary
    except Exception as e:
        logger.warning(f"Failed to load enhanced model: {e}")
        return None

    model = model_data['model']
    feature_names = model_data['feature_names']
    logger.info(f"Loaded enhanced model with {len(feature_names)} features")

    # Prepare features for prediction
    # Ensure all required features are present
    missing_features = set(feature_names) - set(features_df.columns)
    if missing_features:
        logger.warning(f"Missing {len(missing_features)} features, filling with zeros")
        for feat in missing_features:
            features_df[feat] = 0.0

    # Select features in correct order
    X = features_df[feature_names].copy()

    # Handle missing/infinite values
    X = X.replace([np.inf, -np.inf], np.nan)
    X = X.fillna(0)

    # Predict
    predictions = model.predict(X)

    # Build output DataFrame
    output_df = features_df.copy()
    output_df['enhanced_prediction'] = predictions

    # Convert log predictions back to linear scale if needed
    if 'log_enrichment' in str(model_data.get('metadata', {}).get('target_variable', '')):
        output_df['predicted_enrichment'] = 10 ** predictions
    else:
        output_df['predicted_enrichment'] = predictions

    logger.info(f"Enhanced prediction complete")
    logger.info(f"Prediction range: [{predictions.min():.3f}, {predictions.max():.3f}]")

    return output_df


def predict_new_primers_enhanced(df=None, primer_list=None, fg_genome_sequence=None,
                                 conditions=None, primer_positions=None,
                                 use_enhanced=True, model_path=None):
    """
    Unified prediction function supporting both standard and enhanced models.

    Args:
        df: Standard feature DataFrame (for standard mode)
        primer_list: List of primers (for enhanced mode)
        fg_genome_sequence: Genome sequence (for enhanced mode)
        conditions: Reaction conditions (for enhanced mode)
        primer_positions: Position dict (for enhanced mode)
        use_enhanced: Whether to use enhanced features
        model_path: Optional custom model path

    Returns:
        DataFrame with predictions
    """
    if use_enhanced:
        if primer_list is None:
            raise ValueError("primer_list required for enhanced mode")
        if fg_genome_sequence is None:
            raise ValueError("fg_genome_sequence required for enhanced mode")

        result = predict_with_enhanced_features(
            primer_list, fg_genome_sequence, conditions,
            primer_positions, model_path
        )

        if result is not None:
            return result

        # Fall through to standard mode if enhanced model not available
        logger.info("Falling back to standard prediction mode")

    # Standard prediction
    if df is None:
        raise ValueError("df required for standard prediction mode")
    return predict_new_primers(df)


def is_enhanced_model_available(model_path=None):
    """
    Check if enhanced model is available.

    Args:
        model_path: Optional custom model path

    Returns:
        True if enhanced model exists
    """
    if model_path is None:
        model_dir = os.path.join(os.path.dirname(__file__), 'models')
        model_path = os.path.join(model_dir, 'enhanced_rf_model.pkl')
    return os.path.exists(model_path)


def get_enhanced_model_info(model_path=None):
    """
    Get information about the enhanced model.

    Args:
        model_path: Optional custom model path

    Returns:
        Dict with model info or None if not available
    """
    if model_path is None:
        model_dir = os.path.join(os.path.dirname(__file__), 'models')
        model_path = os.path.join(model_dir, 'enhanced_rf_model.pkl')

    if not os.path.exists(model_path):
        return None

    # SECURE: Use load_model_safely
    try:
        model_data = load_model_safely(model_path, verify_hash=False)  # Enhanced models may vary
    except Exception as e:
        logger.warning(f"Failed to load enhanced model info: {e}")
        return None

    return {
        'n_features': len(model_data.get('feature_names', [])),
        'metrics': model_data.get('metrics', {}),
        'metadata': model_data.get('metadata', {}),
        'version': model_data.get('version', 'unknown')
    }


if __name__ == "__main__":
    pd.set_option('display.max_columns', 500)

    # Check enhanced model status
    if is_enhanced_model_available():
        info = get_enhanced_model_info()
        print("Enhanced model available:")
        print(f"  Features: {info['n_features']}")
        print(f"  R-squared: {info['metrics'].get('r2', 'N/A'):.4f}")
    else:
        print("Enhanced model not available")
        print("Run: python scripts/train_enhanced_rf.py --help")

    # Standard mode example
    myco_prefixes = [parameter.data_dir + 'kmer_files/myco']
    print("\nStandard feature example:")
    print(create_augmented_df(myco_prefixes, ['ACAACC','TACGTCA'], molarity=2.5))